import type { ContractInfo } from '@/services/types'

/** 开发环境 mock 合约数据 — 与 mockData.ts 行情数据对应的常见期货合约 */
export const MOCK_CONTRACTS: ContractInfo[] = [
  // 上期所 SHFE
  {
    instrumentID: 'au2506',
    instrumentName: '黄金2506',
    exchangeID: 'SHFE',
    productID: 'au',
    volumeMultiple: 1000,
    priceTick: 0.02,
    expireDate: '2025-06-16',
    isTrading: 1,
    productClass: "1",
  },
  {
    instrumentID: 'au2512',
    instrumentName: '黄金2512',
    exchangeID: 'SHFE',
    productID: 'au',
    volumeMultiple: 1000,
    priceTick: 0.02,
    expireDate: '2025-12-15',
    isTrading: 1,
    productClass: "1",
  },
  {
    instrumentID: 'ag2506',
    instrumentName: '白银2506',
    exchangeID: 'SHFE',
    productID: 'ag',
    volumeMultiple: 15,
    priceTick: 1,
    expireDate: '2025-06-16',
    isTrading: 1,
    productClass: "1",
  },
  {
    instrumentID: 'ag2512',
    instrumentName: '白银2512',
    exchangeID: 'SHFE',
    productID: 'ag',
    volumeMultiple: 15,
    priceTick: 1,
    expireDate: '2025-12-15',
    isTrading: 1,
    productClass: "1",
  },
  {
    instrumentID: 'cu2506',
    instrumentName: '铜2506',
    exchangeID: 'SHFE',
    productID: 'cu',
    volumeMultiple: 5,
    priceTick: 10,
    expireDate: '2025-06-16',
    isTrading: 1,
    productClass: "1",
  },
  {
    instrumentID: 'cu2509',
    instrumentName: '铜2509',
    exchangeID: 'SHFE',
    productID: 'cu',
    volumeMultiple: 5,
    priceTick: 10,
    expireDate: '2025-09-15',
    isTrading: 1,
    productClass: "1",
  },
  {
    instrumentID: 'rb2506',
    instrumentName: '螺纹钢2506',
    exchangeID: 'SHFE',
    productID: 'rb',
    volumeMultiple: 10,
    priceTick: 1,
    expireDate: '2025-06-16',
    isTrading: 1,
    productClass: "1",
  },
  {
    instrumentID: 'rb2510',
    instrumentName: '螺纹钢2510',
    exchangeID: 'SHFE',
    productID: 'rb',
    volumeMultiple: 10,
    priceTick: 1,
    expireDate: '2025-10-15',
    isTrading: 1,
    productClass: "1",
  },
  // 中金所 CFFEX
  {
    instrumentID: 'IF2506',
    instrumentName: '沪深300指数2506',
    exchangeID: 'CFFEX',
    productID: 'IF',
    volumeMultiple: 300,
    priceTick: 0.2,
    expireDate: '2025-06-20',
    isTrading: 1,
    productClass: "1",
  },
  {
    instrumentID: 'IF2509',
    instrumentName: '沪深300指数2509',
    exchangeID: 'CFFEX',
    productID: 'IF',
    volumeMultiple: 300,
    priceTick: 0.2,
    expireDate: '2025-09-19',
    isTrading: 1,
    productClass: "1",
  },
  {
    instrumentID: 'IC2506',
    instrumentName: '中证500指数2506',
    exchangeID: 'CFFEX',
    productID: 'IC',
    volumeMultiple: 200,
    priceTick: 0.2,
    expireDate: '2025-06-20',
    isTrading: 1,
    productClass: "1",
  },
  {
    instrumentID: 'IH2506',
    instrumentName: '上证50指数2506',
    exchangeID: 'CFFEX',
    productID: 'IH',
    volumeMultiple: 300,
    priceTick: 0.2,
    expireDate: '2025-06-20',
    isTrading: 1,
    productClass: "1",
  },
  // 大商所 DCE
  {
    instrumentID: 'm2509',
    instrumentName: '豆粕2509',
    exchangeID: 'DCE',
    productID: 'm',
    volumeMultiple: 10,
    priceTick: 1,
    expireDate: '2025-09-15',
    isTrading: 1,
    productClass: "1",
  },
  {
    instrumentID: 'i2509',
    instrumentName: '铁矿石2509',
    exchangeID: 'DCE',
    productID: 'i',
    volumeMultiple: 100,
    priceTick: 0.5,
    expireDate: '2025-09-15',
    isTrading: 1,
    productClass: "1",
  },
  // 郑商所 CZCE
  {
    instrumentID: 'SR509',
    instrumentName: '白糖509',
    exchangeID: 'CZCE',
    productID: 'SR',
    volumeMultiple: 10,
    priceTick: 1,
    expireDate: '2025-09-15',
    isTrading: 1,
    productClass: "1",
  },
  {
    instrumentID: 'TA509',
    instrumentName: 'PTA509',
    exchangeID: 'CZCE',
    productID: 'TA',
    volumeMultiple: 5,
    priceTick: 2,
    expireDate: '2025-09-15',
    isTrading: 1,
    productClass: "1",
  },
]
